### ISSUE TITLE
Search Docs

### ISSUE THREAD

**Issue by skipjack** [skipjack/react-banner#11]
@dzello I'd like to use algolia/docsearch for the demo if possible? If you'd be willing to help, I have a few quick questions. I have some ideas for tweaking the behavior and whatever we do here will feed into the webpack.js.org once I integrate.

> Background: This package is basically a cleaned up, enhanced, open-source version of the `Navigation` component we created over at the main repo.

**Comment by joshed-io** [comment]
Looks great! Should be no issues to use DocSearch. What q's do you have?

**Comment by skipjack** [comment]
Remember when I first tried implementing it via a custom component, i.e. only interfacing with the docsearch api, and I ran into some issues getting results? Probably just overlooked something, but I remember reviewing the code with you which you said looked kosher. Anyway, just in case I hit that again I may ping you with some questions re hitting the api directly.

Also, the docsearch autocomplete that we're currently using on webpack.js.org requires ownership of the `<input>` element. I was wondering if there's anyway around this aside from writing a custom component? Is there any mechanism by which I can just pipe the current input to the component?

Aside from those that's pretty much it... I'd just have to go through getting a docsearch key setup for this documentation site. It's currently an SPA, so I don't know if that complicates things...

**Comment by joshed-io** [comment]
I do remember, yes. I believe it was that the taking of the search box in and out of the DOM was creating issues.

Good question re: what can be done with the DocSearch autocomplete. The [code is here](https://github.com/algolia/docsearch/blob/master/src/lib/DocSearch.js) and it's not too complex - do you see any easy wins to implement it in a different way?

It's okay if the site is an SPA, we have a setting where we can do the crawling from a headless browser with JS support.

**Comment by skipjack** [comment]
> I do remember, yes. I believe it was that the taking of the search box in and out of the DOM was creating issues.

Yea that was one of a few issues. The re-inserted `<input>` element was caused by preact I believe so I may have to ping someone else when re-integrating it into the site.

> Good question re: what can be done with the DocSearch autocomplete. The code is here and it's not too complex - do you see any easy wins to implement it in a different way?

Sounds good, I'll take a look once I start on this. Maybe I can suggest and possibly PR some changes over there.

> It's okay if the site is an SPA, we have a setting where we can do the crawling from a headless browser with JS support.

Awesome. So I'll sign up at docsearch and see how far I can get in the implementation and then ping you if I have any questions, sound good? Should be a lot easier to discuss once I have something in place.

**Comment by joshed-io** [comment]
Sounds good and happy to take any PRs that makes the component more extensible!

**Comment by skipjack** [comment]
@dzello finally digging back into this sorry for the long delay (been super busy with webpack.js.org and my normal job). I signed up with docsearch over the summer and just started digging through the `DocSearch.js` code and hitting the API. I am able to get results when hitting the API directly, not sure what was going wrong the last time I tried.

I don't have any questions yet but will ping you if I do. I essentially just want to separate the input handling/search logic from the result display. I also may try to convert some the display/formatting logic to a react component. Let me know if you see any red flags in that plan and, if not, I'll just keep you up to date as I go.

**Comment by joshed-io** [comment]
@skipjack Cool! Sounds like a solid plan to me. DocSearch.js is a light wrapper around [autocomplete.js](https://github.com/algolia/autocomplete.js/), so if you go about separating concerns looking into how that works might be helpful. If you need to go down a level, than you can use the [Algolia JavaScript API client](https://github.com/algolia/algoliasearch-client-javascript) directly.

**Comment by skipjack** [comment]
Made a lot of progress today -- should have something ready to go later this week... here's a quick screenshot:

![image](https://user-images.githubusercontent.com/8988697/31577829-996d4e1e-b0e3-11e7-91a0-21b218533448.png)

Essentially I just took the `formatHits` / `formatURL` methods into a react component and used the `suggestion` template from `templates.js` within the new component's `render` method. So basically I'm using the `algoliasearch` client to hit the API directly and then passing the results down to that `SearchResults` component I just described (shown in screenshot).

So, still some work to do, but I haven't hit any major blockers yet. Seems this path should work, and I'd be happy to pass this code back to you guys for open source usage in the react community. I'm sure it'll need some fine tuning as there's probably some edge cases I'm not taking into account.

**Comment by joshed-io** [comment]
Screenshot looks good! And I don't see any issue with that approach. We'll be very happy to make it available to our React users once it's ready 🎉

**Comment by skipjack** [comment]
@dzello done! Pushed to the [docs/demo site](https://skipjack.github.io/react-banner/).

![image](https://user-images.githubusercontent.com/8988697/31749176-56fb6456-b446-11e7-9ad4-6d94dc26cb68.png)

It doesn't have everything built in, e.g. key bindings, but I think it's pretty solid so far. All the display related code can be found [here](https://github.com/skipjack/react-banner/tree/master/src/search-results). Let me know what you think, happy to help push it further though I think we should discuss direction a bit. It seems this could go one of two ways...

1. Do it the "react way" and translate most of the existing rendering/display logic to react.
2. Refactor the js implementation Algolia already has for usage in simpler wrapper components.

I started going down the first route a bit but the second probably makes more sense to avoid duplication between different view implementations (angular, react, vue, etc.). I think if the logic is separated as such:

- Input (Display Logic)
- Search Results (Display Logic)
- Caching/Search Logic

It seems a lot of the code is already isolated logically (i.e. separated into different functions), but not into separate modules (i.e. display and search/caching functions are mixed together in the same classes). Once separated, it should be easy to write simple components/views in any framework that simply import and utilize the display logic. Then, in react for example, users could either use `<SearchInput>` or `<SearchResults>`. Or they could simply import a component that utilizes both under the hood, i.e. `<Autocomplete>`.

Closing, as this issue is resolved, but feel free to continue the discussion here. Not sure how much your company would want to pursue this direction but I could see it being useful. Not only for docsearch, but really any users of the algolia api.

**Comment by joshed-io** [comment]
Thanks @skipjack! I just played with the demo - really nice. The next step would be to help Algolia users find it so they can use it or provide feedback. For that I'd suggest making a post on our forum's [Show & Tell category](https://discourse.algolia.com/c/show-tell). You can tag the topic React and autocomplete so it's easy to find. Also, maybe worth mentioning Algolia somewhere in the documentation, so if someone searches for it they can see how to wire it up for their Algolia index.

**Comment by skipjack** [comment]
Sounds good... yeah I was planning to add a search page in the "Integrations" section that mentions Algolia. `react-banner` will likely get a bit more attention once we've incorporated it into webpack.js.org so that may help as well. I'll reopen so I don't forget to hit these things:

- [x] Add search page to the _Integrations_ section.
- [ ] Separate `SearchResults` to a separate repo and post about it [here][1].

[1]: https://discourse.algolia.com/c/show-tell

**Comment by skipjack** [comment]
Unfortunately I don't really have time to separate out and maintain a repo for those components but it is [mentioned](https://skipjack.github.io/react-banner/integration/search) in the latest v1 docs. If someone else has some time to split out a separate `react-algolia-something` package they're totally welcome to grab this as a baseline.
