### ISSUE TITLE
Start Documentation

### ISSUE THREAD

**Issue by skipjack** [skipjack/react-banner#3]
Start documenting the available props/features and consider using a static site generator (e.g. `gatsby`, `antwar` or others).

**Comment by bebraw** [comment]
[styleguidist](https://github.com/styleguidist/react-styleguidist) might be a nice starting point. Great for components.

**Comment by skipjack** [comment]
Ok from a functionality standpoint, I have the components and documentation site in pretty good shape. I finished the readme and now just have to fill in all the content for the documentation site, which I keep procrastinating. This is my main focus for now. Once it's there I'll publish to npm, ask a few ppl to review and give feedback, and call it ready for use in the wild.

**Comment by skipjack** [comment]
Docs are pretty much done, adding the react-sidebar integration doc tonight and doing another release.
