### ISSUE TITLE
Deploy via gh-pages

### ISSUE THREAD

**Issue by skipjack** [skipjack/react-banner#4]
Stub.

**Comment by skipjack** [comment]
Rough draft of this is up [here](https://skipjack.github.io/react-banner/). Can't rewrite 404's to the index with gh-pages but I'll be turning the docs folder into a static site soon... just doing some testing to get it working with react-router.

@bebraw I'm closing this for now as I think the gh-pages setup is ok, but feel free to re-open if you think there's a better approach.

**Comment by bebraw** [comment]
FYI, you can rewrite 404s like [this](https://github.com/rafrex/spa-github-pages). Maybe that would work.

**Comment by skipjack** [comment]
@bebraw exactly what I was looking for and couldn't find yesterday. I knew somebody must have had a hack out there for that... thanks!
